# This is a basic workflow to help you get started with Actions

name: Build on macOS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install GitHub CLI
        run: |
          brew update
          brew install gh
      - name: Install dependencies
        run: |
          brew update
          brew install cmake eigen glew pkgconfig freeglut opencv@3
          
      - name: Register opencv@3
        run: |
          echo 'export PATH="/usr/local/opt/opencv@3/bin:$PATH"' >> /Users/runner/.bash_profile
          source ~/.bash_profile
          export LDFLAGS="-L/usr/local/opt/opencv@3/lib"
          export CPPFLAGS="-I/usr/local/opt/opencv@3/include"
          export PKG_CONFIG_PATH="/usr/local/opt/opencv@3/lib/pkgconfig"

      - name: Try compilation
        run: |
           "${GITHUB_WORKSPACE}/Build.sh"
